name: AWS Multienvironemnt Deployment

on:
  push:
    branches:
      # - dev          # Auto-deploy to Dev
      # - uat          # Auto-deploy to UAT
      # - prod         # Requires manual approval for Production
       - main      

  # pull_request:
  #   branches:
  #     - production   # Run tests before merging into production

  # workflow_dispatch: # Allows manual trigger

  # env:
  #   AWS_REGION: ap-southeast-1

jobs:
  # deploy_dev:
  #   if: github.ref == 'refs/heads/dev'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
      
  #     - name: Run Linting
  #       run: npm run lint

  #     - name: Run Unit Tests
  #       run: npm test
      
  #     - name: Run Basic Integration Tests
  #       run: npm run test:integration
      
  #     - name: Terraform Plan (Dev)
  #       run: terraform plan

  # deploy_uat:
  #   if: github.ref == 'refs/heads/uat'
  #   runs-on: ubuntu-latest
  #   needs: deploy_dev
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Run Linting
  #       run: npm run lint

  #     - name: Run Unit Tests
  #       run: npm test

  #     - name: Run Full Integration Tests
  #       run: npm run test:full-integration

  #     - name: Run Load/Performance Tests
  #       run: npm run test:performance

  #     - name: Run Security Scans
  #       run: npm run test:security

  #     - name: Terraform Apply (UAT)
  #       run: terraform apply -auto-approve

  deploy_prod:
    # if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    # needs: deploy_uat  # Ensures UAT is deployed before PROD
    # environment: production  # Requires manual approval
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Linting
        run: npm run lint

      - name: Run Unit Tests
        run: npm test

      - name: Run Full Integration Tests
        run: npm run test:full-integration

      - name: Run Smoke Tests
        run: npm run test:smoke

      - name: Manual Approval Required
        uses: hmarr/auto-approve-action@v3

      - name: Terraform Apply (Prod)
        run: terraform apply -auto-approve

